stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - production
  only:
    - main
  script:
    - cp $CI_PROJECT_DIR/ManiaMapper.py /mnt/data/maniamapper/
    - cp $CI_PROJECT_DIR/requirements.txt /mnt/data/maniamapper/
    - cd /mnt/data/maniamapper
    - source venv/bin/activate
    - pip install -r requirements.txt --quiet
    - echo "Deploy complete"
