stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - production
  only:
    - main
  script:
    - cp -r $CI_PROJECT_DIR/. /home/deploy/maniamapper/
    - cd /home/deploy/maniamapper
    - source venv/bin/activate
    - pip install -r requirements.txt --quiet
    - echo "Deploy complete"
