stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - production
  only:
    - main
  script:
    - cd $CI_PROJECT_DIR && git lfs pull
    - cp $CI_PROJECT_DIR/ManiaMapper.py /opt/maniamapper/
    - cp $CI_PROJECT_DIR/app.py /opt/maniamapper/
    - cp $CI_PROJECT_DIR/requirements.txt /opt/maniamapper/
    - cp -r $CI_PROJECT_DIR/static /opt/maniamapper/
    - '[ -f $CI_PROJECT_DIR/mania_model.pt ] && cp $CI_PROJECT_DIR/mania_model.pt /opt/maniamapper/ || true'
    - cd /opt/maniamapper
    - source venv/bin/activate
    - pip install -r requirements.txt --quiet
    - sudo systemctl restart maniamapper
    - echo "Deploy complete"
